// <auto-generated />
using System;
using ApiPeliculas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PropiedadesMinimalApi.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropiedadesMinimalApi.Modelo.Propiedad", b =>
                {
                    b.Property<int>("IdPropiedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPropiedad"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPropiedad");

                    b.ToTable("Propiedad");

                    b.HasData(
                        new
                        {
                            IdPropiedad = 1,
                            Activa = true,
                            Descripcion = "casa desc 1",
                            FechaCreacion = new DateTime(2025, 11, 16, 16, 37, 0, 416, DateTimeKind.Local).AddTicks(263),
                            Nombre = "casa 1",
                            Ubicacion = "mexico"
                        },
                        new
                        {
                            IdPropiedad = 2,
                            Activa = true,
                            Descripcion = "casa desc 2",
                            FechaCreacion = new DateTime(2025, 11, 16, 16, 37, 0, 416, DateTimeKind.Local).AddTicks(312),
                            Nombre = "casa 2",
                            Ubicacion = "mexico"
                        },
                        new
                        {
                            IdPropiedad = 3,
                            Activa = true,
                            Descripcion = "casa desc 3",
                            FechaCreacion = new DateTime(2025, 11, 16, 16, 37, 0, 416, DateTimeKind.Local).AddTicks(318),
                            Nombre = "casa 3",
                            Ubicacion = "mexico"
                        },
                        new
                        {
                            IdPropiedad = 4,
                            Activa = true,
                            Descripcion = "casa desc 4",
                            FechaCreacion = new DateTime(2025, 11, 16, 16, 37, 0, 416, DateTimeKind.Local).AddTicks(323),
                            Nombre = "casa 4",
                            Ubicacion = "mexico"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
